### ISSUE TITLE
How to display the current user information from firebase ?

### ISSUE THREAD

**Issue by Drozerah** [CaptainYouz/vue-firebase-tutorial#1]
Hi Anas !

I Have followed your great tutorial and I thank you very much for its quality and well explained details !  Firebase, Vue.js and Node.js as a FVN stack is promising without a doubt ! As a request to your september update on medium, I'd like to  know how to display the current user email or other user information from firebase into the Hello.vue ? 

Drozerah from France ;)

**Comment by Turqueso** [comment]
You could start looking into vuex so you can save locally the user info then show it like any other data

**Comment by CaptainYouz** [comment]
Hi Drozerah!
Sorry for the late response. Well, the `onAuthStateChanged` return the current user signed-in. This object contains some information about the user, such as his UID, email etc. You can check the doc here: https://firebase.google.com/docs/reference/js/firebase.User for the complete object methods.
