### ISSUE TITLE
A lot of missing directories

### ISSUE THREAD

**Issue by OTANatio** [CaptainYouz/vue-firebase-tutorial#6]
I downloaded the file and i ran the npm commands but keeps giving me error messages.

**Comment by dariushazimi** [comment]
same here

**Comment by OTANatio** [comment]
I solved the problem, add me up on WhatsApp +2348125338864

Would love to share the solutions with you

**Comment by OTANatio** [comment]
Its a simple import problem,

You've got to import both firebase and vuefire .

My mistake was that I only imported vuefire...
